In [1]:
from numpy import *

In [2]:
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
eye(1000)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [5]:
print(pi)

3.141592653589793


In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5],dtype=complex, ndmin = 2)
print(a)

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]]


In [9]:
teacher = np.dtype([('name','S20'),('age','i1'),('salary','f4')])
print(teacher)

[('name', 'S20'), ('age', 'i1'), ('salary', '<f4')]


In [10]:
b = np.array([('ycs', 32, 6357),('jxe', 28, 6856)], dtype = teacher) 
print(b)

[(b'ycs', 32, 6357.) (b'jxe', 28, 6856.)]


In [11]:
import numpy as np
ndarray = np.arange(1,13).reshape(3,4)

In [12]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
2*3

6

TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
a = np.arange(24) 
print(a.ndim)

1


In [19]:
b = a.reshape(3,4,2)

In [20]:
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [21]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


In [22]:
print(b.shape)

(3, 4, 2)


In [26]:
x = np.empty([3,2], dtype = int) #問他empty
print(x)

[[-6917529027641081856 -6917529027641081856]
 [                   4                   -1]
 [-6917529027641081856 -6917529027641081856]]


In [30]:

l = b'hello world' 
print(type(l))


<class 'bytes'>


In [31]:
a = np.frombuffer(l, dtype = "S1") 

In [32]:
print(a)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']
